---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: docker-registry
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
    release: docker-registry
  type: NodePort
