# device-mapper-multipath configuration file

# For a complete list of the default configuration values, run either:
# # multipath -t
# or
# # multipathd show config

# For a list of configuration options with descriptions, see the
# multipath.conf man page.

# set user_friendly_names to no to ensure we have /dev/mapper/[WWID] form
# in case /dev/mapper/mpatha referring to different volumes between reboots

defaults {
    user_friendly_names no
    find_multipaths on
}

blacklist {
}
