{
 "title": "Device",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"ipmi_sensor\" WITH KEY = \"host\""
   },
   {
    "name": "GPU_HOST",
    "label": "GPU Host",
    "query": "SHOW TAG VALUES FROM \"gpu.host\" WITH KEY = \"host\""
   },
   {
    "name": "GPU_PCIID",
    "label": "GPU PCI Address",
    "query": "SHOW TAG VALUES FROM \"gpu.host\" WITH KEY = \"pciid\" WHERE host =~ /^$GPU_HOST$/"
   }
  ]
 },
 "panels": [
  { "title": "Chassis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "RPM / Percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND hostname=~ /^$HOST$/ AND \"name\" !~ /^*_usage$/ AND (\"unit\" = 'percent' OR \"unit\" = 'rpm')) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "!=", "value": "cube" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" },
      { "condition": "AND", "key": "name", "operator": "!=", "value": "*_usage" },
      { "condition": "OR", "key": "unit", "operator": "=", "value": "rpm" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "!=", "value": "cube" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "!=", "value": "cube" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "watts" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "!=", "value": "cube" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "volts" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "!=", "value": "cube" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "amps" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" = '$HOST' AND \"cpu\" = 'cpu-total') AND $timeFilter",
       "select": [
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "* -1 + 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT last(\"available_percent\") * -1 + 100 FROM \"mem\" WHERE (\"host\" = '$HOST') AND $timeFilter",
       "select": [
        [
         { "params": [ "available_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "* -1 + 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Partition Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
     "repeat": "path",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT last(\"used_percent\") FROM \"disk\" WHERE (\"host\" = '$HOST' AND (\"path\" = '/' OR \"path\" = '\\\\C:')) AND $timeFilter",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 20 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Core",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Ping",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "ipmi_sensor",
       "query": "SELECT mean(\"resp\") FROM \"def\".\"ipmi_sensor\" WHERE (\"name\" = 'ping_checker' AND \"hostname\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"ip\"",
       "select": [
        [
         { "params": [ "resp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "ping_checker" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$HOST$/" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 23 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Free Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 23 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\") AS \"system\", mean(\"usage_iowait\") AS \"iowait\" FROM \"cpu\" WHERE (\"host\" = '$HOST') AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1 min" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5 min" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "15 min" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Swap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Partition",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT mean(\"total\") AS \"total\", mean(\"used\") AS \"used\" FROM \"disk\" WHERE (\"host\" = '$HOST' AND (\"path\" = '/' OR \"path\" = '\\\\C:')) AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
       ]
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "description": "Physical GPU compute workload % per card. Grouped by PCI ID and GPU model name. Peak and average of 1-second samples over each 5-minute window: a workload shorter than about 15 seconds at the end of a window may not appear.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "util_gpu_max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$GPU_HOST$/" },
        { "condition": "AND", "key": "pciid", "operator": "=~", "value": "/^$GPU_PCIID$/" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "alias": "Peak — $tag_name ($tag_pciid)"
      },
      {
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "util_gpu_mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$GPU_HOST$/" },
        { "condition": "AND", "key": "pciid", "operator": "=~", "value": "/^$GPU_PCIID$/" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "alias": "Avg — $tag_name ($tag_pciid)"
      }
     ]
    },
    {
     "title": "GPU VRAM Usage",
     "type": "timeseries",
     "description": "Physical GPU framebuffer (VRAM) used and total per card in MiB. On a card carved into vGPUs, 'used' is the framebuffer allocated to running vGPU VMs: it steps when a VM starts or stops, not when a workload inside a VM allocates memory. Sampled every 5 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "mem_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$GPU_HOST$/" },
        { "condition": "AND", "key": "pciid", "operator": "=~", "value": "/^$GPU_PCIID$/" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "alias": "Used — $tag_name ($tag_pciid)"
      },
      {
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "mem_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$GPU_HOST$/" },
        { "condition": "AND", "key": "pciid", "operator": "=~", "value": "/^$GPU_PCIID$/" }
       ],
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "alias": "Total — $tag_name ($tag_pciid)"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffics",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) AS \"in\", non_negative_derivative(mean(\"bytes_sent\"), 1s) AS \"out\" FROM \"net\" WHERE (\"host\" = '$HOST' AND \"interface\" =~ /^$IFACES$/) AND $timeFilter GROUP BY time($interval), \"interface\" fill(null)",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Network Packet Rate ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(sum(\"bytes_recv\"), 1s) as \"in\"  FROM \"net\" WHERE \"host\" =~ /^$server$/ AND \"interface\" =~ /^$int$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Packet Drops",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "Packets" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_difference(mean(\"drop_in\")) AS \"in\", non_negative_difference(mean(\"drop_out\")) AS \"out\" FROM \"net\" WHERE (\"host\" = '$HOST' AND \"interface\" =~ /^$IFACES$/) AND $timeFilter GROUP BY time($interval), \"interface\"",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Packet Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short", "label": "Packets" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(sum(\"bytes_recv\"), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND \"interface\" =~ /^$int$/ AND $timeFilter GROUP BY time($interval) fill(none)",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "repeat": "DISKS",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]].$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\", non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST') AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "repeat": "DISKS",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]].$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" }
       ]
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "repeat": "DISKS",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]].$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"write_time\")) / non_negative_difference(mean(\"writes\")) AS \"write\", non_negative_difference(mean(\"read_time\")) / non_negative_difference(mean(\"reads\")) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST') AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}