{
 "title": "Top Hosts",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "TOP", "label": "Top", "query": "1,2,3,4,5,6,7,8,9,10" },
   {
    "name": "HOSTS",
    "label": "Host(s)",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\" WHERE role = 'cube'"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Uptime",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT top(last, \"host\", $TOP) FROM (SELECT last(\"uptime\") FROM \"system\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/) AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top CPU Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT top(mean, \"host\", $TOP) FROM (SELECT mean(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Memory Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT top(mean, \"host\", $TOP) FROM (SELECT mean(\"available_percent\") * -1 + 100 FROM \"mem\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/) AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Partition Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT top(mean, \"host\", $TOP) FROM (SELECT mean(\"used_percent\") FROM \"disk\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"path\" = '/') AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Temperature",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT top(mean, host, \"name\", $TOP) FROM (SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE role = 'cube' AND unit = 'degrees_c' AND \"host\" =~ /^$HOSTS$/ AND $timeFilter GROUP BY \"host\", \"name\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Power Compsumtion",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT top(mean, host, \"name\", $TOP) FROM (SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE role = 'cube' AND unit = 'watts' AND \"host\" =~ /^$HOSTS$/ AND $timeFilter GROUP BY \"host\", \"name\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Top Bandwidth", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 } },
  { "title": "Top IOPS", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 } },
  {
   "title": "Write Bandwidth",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(mean, $TOP), \"name\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"write_bytes\", 1s) FROM \"diskio\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"name\" =~ /^(sd[a-z]+|nvme[0-9]+n[0-9]+)$/) AND $timeFilter GROUP BY \"host\", \"name\") GROUP BY \"host\", \"name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(mean, $TOP), \"name\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"read_bytes\", 1s) FROM \"diskio\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"name\" =~ /^(sd[a-z]+|nvme[0-9]+n[0-9]+)$/) AND $timeFilter GROUP BY \"host\", \"name\") GROUP BY \"host\", \"name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(mean, $TOP), \"name\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"writes\", 1s) FROM \"diskio\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"name\" =~ /^(sd[a-z]+|nvme[0-9]+n[0-9]+)$/) AND $timeFilter GROUP BY \"host\", \"name\") GROUP BY \"host\", \"name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(mean, $TOP), \"name\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"reads\", 1s) FROM \"diskio\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"name\" =~ /^(sd[a-z]+|nvme[0-9]+n[0-9]+)$/) AND $timeFilter GROUP BY \"host\", \"name\") GROUP BY \"host\", \"name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Top Latency", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 16 } },
  {
   "title": "Write Latency",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(mean, $TOP), \"name\", \"host\" FROM (SELECT mean(\"latency\") FROM (SELECT non_negative_difference(\"write_time\") / non_negative_difference(\"writes\") AS \"latency\" FROM \"diskio\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"name\" =~ /^(sd[a-z]+|nvme[0-9]+n[0-9]+)$/) AND $timeFilter GROUP BY \"host\", \"name\") GROUP BY \"host\", \"name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(mean, $TOP), \"name\", \"host\" FROM (SELECT mean(\"latency\") FROM (SELECT non_negative_difference(\"read_time\") / non_negative_difference(\"reads\") AS \"latency\" FROM \"diskio\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"name\" =~ /^(sd[a-z]+|nvme[0-9]+n[0-9]+)$/) AND $timeFilter GROUP BY \"host\", \"name\") GROUP BY \"host\", \"name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    { "title": "Top Traffics", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 } },
    { "title": "Top Packet Rate", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 } },
    {
     "title": "In Traffics",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(mean, $TOP), \"interface\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"bytes_recv\", 1s) FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Out Traffics",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(mean, $TOP), \"interface\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"bytes_sent\", 1s) FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "In Rate",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(mean, $TOP), \"interface\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"packets_recv\", 1s) FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Out Rate",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(mean, $TOP), \"interface\", \"host\" FROM (SELECT mean(non_negative_derivative) FROM (SELECT non_negative_derivative(\"packets_sent\", 1s) FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    { "title": "Top Packet Drops", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 16 } },
    { "title": "Top Packet Errors", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 16 } },
    {
     "title": "In Drops",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(sum, $TOP), \"interface\", \"host\" FROM (SELECT sum(non_negative_difference) FROM (SELECT non_negative_difference(\"drop_in\") FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Out Drops",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(sum, $TOP), \"interface\", \"host\" FROM (SELECT sum(non_negative_difference) FROM (SELECT non_negative_difference(\"drop_out\") FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "In Errors",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(sum, $TOP), \"interface\", \"host\" FROM (SELECT sum(non_negative_difference) FROM (SELECT non_negative_difference(\"err_in\") FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Out Errors",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(sum, $TOP), \"interface\", \"host\" FROM (SELECT sum(non_negative_difference) FROM (SELECT non_negative_difference(\"err_out\") FROM \"net\" WHERE role = 'cube' AND (\"host\" =~ /^$HOSTS$/ AND \"interface\" =~ /^eth[0-9]+$/) AND $timeFilter GROUP BY \"host\", \"interface\") GROUP BY \"host\", \"interface\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}