{
 "title": "Host",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"host\" WHERE role = 'cube'"
   },
   {
    "name": "IFACES",
    "label": "Interface(s)",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE \"host\" = '$HOST'"
   },
   {
    "name": "DISKS",
    "label": "Disk(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE \"host\" = '$HOST'"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" = '$HOST' AND \"cpu\" = 'cpu-total') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT last(\"available_percent\") * -1 + 100 FROM \"mem\" WHERE (\"host\" = '$HOST') AND $timeFilter",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Partition Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "repeat": "path",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\") FROM \"disk\" WHERE (\"host\" = '$HOST' AND \"path\" = '/') AND $timeFilter",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Core",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "host.health",
     "query": "SELECT mean(\"resp\") FROM \"def\".\"host.health\" WHERE (\"host\" =~ /^$HOST$/) AND $timeFilter GROUP BY \"ip\", \"type\"",
     "select": [
      [
       { "params": [ "resp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") AS \"user\", mean(\"usage_system\") AS \"system\", mean(\"usage_iowait\") AS \"iowait\" FROM \"cpu\" WHERE (\"host\" = '$HOST') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1 min" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5 min" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "15 min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" }
     ]
    }
   ]
  },
  {
   "title": "Partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$HOST" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Speed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "RPM / Percent" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" = 'cube' AND \"host\" =~ /^$HOST$/ AND \"name\" !~ /^*_usage$/ AND (\"unit\" = 'percent' OR \"unit\" = 'rpm')) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "role", "operator": "!=", "value": "cube" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" },
        { "condition": "AND", "key": "name", "operator": "!=", "value": "*_usage" },
        { "condition": "OR", "key": "unit", "operator": "=", "value": "rpm" }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "role", "operator": "=", "value": "cube" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" },
        { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" }
       ]
      }
     ]
    },
    {
     "title": "Power Consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "role", "operator": "=", "value": "cube" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" },
        { "condition": "AND", "key": "unit", "operator": "=", "value": "watts" }
       ]
      }
     ]
    },
    {
     "title": "Power Voltage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "role", "operator": "=", "value": "cube" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" },
        { "condition": "AND", "key": "unit", "operator": "=", "value": "volts" }
       ]
      }
     ]
    },
    {
     "title": "Power Current",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "query": "SELECT mean(\"value\") FROM \"def\".\"ipmi_sensor\" WHERE (\"role\" != 'cube' AND \"host\" =~ /^$HOST$/ AND \"unit\" = 'degrees_c') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "role", "operator": "=", "value": "cube" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HOST$/" },
        { "condition": "AND", "key": "unit", "operator": "=", "value": "amps" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffics - $IFACES",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) AS \"in\", non_negative_derivative(mean(\"bytes_sent\"), 1s) AS \"out\" FROM \"net\" WHERE (\"host\" = '$HOST' AND \"interface\" =~ /^$IFACES$/) AND $timeFilter GROUP BY time($interval), \"interface\" fill(null)",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/$IFACES/" }
       ]
      }
     ]
    },
    {
     "title": "Network Packet Rate - $IFACES",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(sum(\"bytes_recv\"), 1s) as \"in\"  FROM \"net\" WHERE \"host\" =~ /^$server$/ AND \"interface\" =~ /^$int$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/$IFACES/" }
       ]
      }
     ]
    },
    {
     "title": "Packet Drops - $IFACES",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Packets" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_difference(mean(\"drop_in\")) AS \"in\", non_negative_difference(mean(\"drop_out\")) AS \"out\" FROM \"net\" WHERE (\"host\" = '$HOST' AND \"interface\" =~ /^$IFACES$/) AND $timeFilter GROUP BY time($interval), \"interface\"",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/$IFACES/" }
       ]
      }
     ]
    },
    {
     "title": "Packet Errors - $IFACES",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Packets" }
     ],
     "targets": [
      {
       "alias": "$tag_interface - $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_derivative(sum(\"bytes_recv\"), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND \"interface\" =~ /^$int$/ AND $timeFilter GROUP BY time($interval) fill(none)",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$IFACES$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "repeat": "DISKS",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\", non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "repeat": "DISKS",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "repeat": "DISKS",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"write_time\")) / non_negative_difference(mean(\"writes\")) AS \"write\", non_negative_difference(mean(\"read_time\")) / non_negative_difference(mean(\"reads\")) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Bandwidth - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\", non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"write_time\")) / non_negative_difference(mean(\"writes\")) AS \"write\", non_negative_difference(mean(\"read_time\")) / non_negative_difference(mean(\"reads\")) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Bandwidth - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\", non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"write_time\")) / non_negative_difference(mean(\"writes\")) AS \"write\", non_negative_difference(mean(\"read_time\")) / non_negative_difference(mean(\"reads\")) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Bandwidth - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"write\", non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ],
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency - $DISKS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_difference(mean(\"write_time\")) / non_negative_difference(mean(\"writes\")) AS \"write\", non_negative_difference(mean(\"read_time\")) / non_negative_difference(mean(\"reads\")) AS \"read\" FROM \"diskio\" WHERE (\"host\" = '$HOST' AND \"name\" =~ /^$DISKS$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "$HOST" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$DISKS$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] {[[tag_pciid]]}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "util_gpu" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "alias": "Total: [[tag_name]] {[[tag_pciid]]}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "mem_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
       ]
      },
      {
       "alias": "Used: [[tag_name]] {[[tag_pciid]]}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "mem_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
       ]
      }
     ]
    },
    {
     "title": "Encoder Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] {[[tag_pciid]]}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "util_encoder" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Decoder Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] {[[tag_pciid]]}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pciid" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "gpu.host",
       "select": [
        [
         { "params": [ "util_decoder" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Memory Usage (>1GB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_program",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"mb\" FROM \"def\".\"system.usage\" WHERE \"host\" = '$HOST' AND $timeFilter AND \"mb\" > 1024 GROUP BY \"program\", \"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Databases / Logfiles Disk Usage (>100MB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"size\" FROM \"def\".\"system.disk.usage\" WHERE (\"host\" = '$HOST' AND \"path\" != '/var/lib' AND \"path\" != '/var/log') AND $timeFilter AND \"size\" > 100000 GROUP BY \"path\", \"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}