{
 "title": "Top Instances",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "TID" },
   { "name": "TOP", "label": "Top", "query": "5,10,15,20,50" },
   {
    "name": "TENANT",
    "label": "Tenant",
    "query": "label_values(ceilometer_cpu{project=~\".*$TID.*\"}, project_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top CPU Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (clamp_max(rate(ceilometer_cpu{project_name=~\"$TENANT\"}[$__rate_interval]) / 1e7 / ceilometer_vcpus{project_name=~\"$TENANT\"}, 100)))"
    }
   ]
  },
  {
   "title": "Top Memory Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) ((1 - cube_instance_memory_usable_mb{project_name=~\"$TENANT\"} / cube_instance_memory_visible_mb{project_name=~\"$TENANT\"}) * 100))"
    }
   ]
  },
  { "title": "Top Disk Bandwidth", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 8 }, "content": "\n\n\n" },
  { "title": "Top Disk IO Rate", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 8 }, "content": "\n\n\n" },
  {
   "title": "Read Bandwidth",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_disk_device_read_bytes{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_disk_device_write_bytes{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Read IO Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_disk_device_read_requests{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Write IO Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_disk_device_write_requests{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  { "title": "Top Network Traffic", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 17 }, "content": "\n\n\n" },
  { "title": "Top Network Packet Rate", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 17 }, "content": "\n\n\n" },
  {
   "title": "Incoming Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_network_incoming_bytes{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_network_outgoing_bytes{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Incoming Packet Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_network_incoming_packets{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Outgoing Packet Rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "topk($TOP, sum by (resource, name) (rate(ceilometer_network_outgoing_packets{project_name=~\"$TENANT\"}[$__rate_interval])))"
    }
   ]
  }
 ]
}