{
 "title": "Storage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "OSDS",
    "label": "OSD(s)",
    "query": {
     "query": "label_values(ceph_osd_stat_bytes, ceph_daemon)"
    }
   },
   {
    "name": "POOLS",
    "label": "Pool(s)",
    "query": {
     "query": "label_values(ceph_pool_metadata, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ceph_health",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 * \"total_used_bytes\" / \"total_bytes\") as util  FROM \"ceph_usage\" order by desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_osdmap",
     "query": "SELECT last(\"num_osds\") FROM \"ceph_osdmap_cmd\"",
     "select": [
      [
       { "params": [ "num_in_osds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_usage",
     "query": "select last(total_used_bytes) from ceph_usage",
     "select": [
      [
       { "params": [ "total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_usage",
     "query": "select last(total_used_bytes) from ceph_usage",
     "select": [
      [
       { "params": [ "total_used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_usage",
     "query": "select last(total_used_bytes) from ceph_usage",
     "select": [
      [
       { "params": [ "total_avail_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_osdmap",
     "query": "SELECT last(\"num_in_osds\") FROM \"ceph_osdmap_cmd\"",
     "select": [
      [
       { "params": [ "num_in_osds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_osdmap",
     "query": "SELECT last(\"num_up_osds\") FROM \"ceph_osdmap_cmd\"",
     "select": [
      [
       { "params": [ "num_in_osds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum(ceph_osd_stat_bytes)", "legendFormat": "total" },
    { "expr": "sum(ceph_osd_stat_bytes_used)", "legendFormat": "used" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w_in_bytes[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r_out_bytes[$__rate_interval]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r[$__rate_interval]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_w_latency_sum[$__rate_interval])) / sum(rate(ceph_osd_op_w_latency_count[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_r_latency_sum[$__rate_interval])) / sum(rate(ceph_osd_op_r_latency_count[$__rate_interval]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Top OSD Bandwidth",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top OSD IOPS",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top OSD Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, rate(ceph_osd_op_w_in_bytes[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, rate(ceph_osd_op_r_out_bytes[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(5, rate(ceph_osd_op_w[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(5, rate(ceph_osd_op_r[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, rate(ceph_osd_op_w_latency_sum[$__rate_interval]) / rate(ceph_osd_op_w_latency_count[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, rate(ceph_osd_op_r_latency_sum[$__rate_interval]) / rate(ceph_osd_op_r_latency_count[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bandwidth - $OSDS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
     "repeat": "OSDS",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_in_bytes{ceph_daemon=~\"$OSDS\"}[$__rate_interval])",
       "legendFormat": "{{ceph_daemon}} write"
      },
      {
       "expr": "rate(ceph_osd_op_r_out_bytes{ceph_daemon=~\"$OSDS\"}[$__rate_interval])",
       "legendFormat": "{{ceph_daemon}} read"
      }
     ]
    },
    {
     "title": "IOPS - $OSDS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
     "repeat": "OSDS",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w{ceph_daemon=~\"$OSDS\"}[$__rate_interval])",
       "legendFormat": "{{ceph_daemon}} write"
      },
      {
       "expr": "rate(ceph_osd_op_r{ceph_daemon=~\"$OSDS\"}[$__rate_interval])",
       "legendFormat": "{{ceph_daemon}} read"
      }
     ]
    },
    {
     "title": "Latency - $OSDS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
     "repeat": "OSDS",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum{ceph_daemon=~\"$OSDS\"}[$__rate_interval]) / rate(ceph_osd_op_w_latency_count{ceph_daemon=~\"$OSDS\"}[$__rate_interval])",
       "legendFormat": "{{ceph_daemon}} write"
      },
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{ceph_daemon=~\"$OSDS\"}[$__rate_interval]) / rate(ceph_osd_op_r_latency_count{ceph_daemon=~\"$OSDS\"}[$__rate_interval])",
       "legendFormat": "{{ceph_daemon}} read"
      }
     ]
    }
   ]
  },
  {
   "title": "Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bandwidth - $POOLS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
     "repeat": "POOLS",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(ceph_pool_wr_bytes[$__rate_interval]) * on(pool_id) group_left(name) ceph_pool_metadata{name=~\"$POOLS\"}",
       "legendFormat": "{{name}} write"
      },
      {
       "expr": "rate(ceph_pool_rd_bytes[$__rate_interval]) * on(pool_id) group_left(name) ceph_pool_metadata{name=~\"$POOLS\"}",
       "legendFormat": "{{name}} read"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool stored vs raw",
     "type": "timeseries",
     "description": "Ceph pools come from ceph-mgr (ceph_pool_*); other backends have no exporter and report through the storage-usage collector.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceph_pool_stored * on(pool_id) group_left(name) ceph_pool_metadata{name=~\"ephemeral-vms|cinder-volumes|glance-images|k8s-volumes\"}",
       "legendFormat": "{{name}} stored"
      },
      {
       "expr": "ceph_pool_bytes_used * on(pool_id) group_left(name) ceph_pool_metadata{name=~\"ephemeral-vms|cinder-volumes|glance-images|k8s-volumes\"}",
       "legendFormat": "{{name}} raw"
      },
      { "expr": "cube_storage_pool_stored_bytes", "legendFormat": "{{pool}} stored" }
     ]
    },
    {
     "title": "Pool provisioned vs capacity",
     "type": "timeseries",
     "description": "Provisioned is summed from the collector disk rows; capacity is ceph-mgr stored + max_avail.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pool) (cube_storage_disk_provisioned_bytes) / on(pool) group_left label_replace(sum by (name) ((ceph_pool_stored + ceph_pool_max_avail) * on(pool_id) group_left(name) ceph_pool_metadata{name=~\"ephemeral-vms|cinder-volumes|glance-images|k8s-volumes\"}), \"pool\", \"$1\", \"name\", \"(.*)\")",
       "legendFormat": "{{pool}} over-subscription"
      }
     ]
    }
   ]
  }
 ]
}