apiVersion: 1

datasources:
- name: influxdb-telegraf
  type: influxdb
  access: proxy
  database: telegraf
  url: http://localhost:8086
  jsonData:
     timeInterval: "1m"
  editable: true

- name: influxdb-ceph
  type: influxdb
  access: proxy
  database: ceph
  url: http://localhost:8086
  jsonData:
     timeInterval: "1m"
  editable: true

- name: influxdb-monasca
  type: influxdb
  access: proxy
  database: monasca
  url: http://localhost:8086
  jsonData:
     timeInterval: "1m"
  editable: true

- name: influxdb-monasca-flux
  type: influxdb
  access: proxy
  url: http://localhost:8086
  jsonData:
    defaultBucket: monasca/def
    httpMode: POST
    organization: cube
    version: Flux
  secureJsonData:
    token: cube
  editable: true

- name: influxdb-events
  type: influxdb
  access: proxy
  database: events
  url: http://localhost:8086
  jsonData:
     timeInterval: "1m"
  editable: true

- name: Dashboard1
  type: prometheus
  access: proxy
  database:
  url: http://localhost:9091/prometheus
  jsonData:
     timeInterval: "1m"
  editable: true
