---
# file: roles/lmi/tasks/main.yml

- name: Create lmi directory layout
  file: path={{lmi_root}}/{{item}} state=directory owner=www-data group=www-data mode=0775
  with_items:
    - public
    - public/fonts
    - public/icons
    - public/images
    - public/styles
    - public/scripts
    - views
  when: deploy_full == "1"

- name: Assure lmi static files are properly installed
  copy: src=./static/{{item.src}} dest={{lmi_root}}/public/{{item.dest}} owner=www-data group=www-data mode=644
  with_items:
    - { src: 'fonts/', dest: 'fonts' }
    - { src: 'icons/', dest: 'icons' }
    - { src: 'images/', dest: 'images' }
    - { src: 'styles/', dest: 'styles' }
    - { src: 'scripts/', dest: 'scripts' }
    - { src: 'favicon.png', dest: '' }
  when: deploy_full == "1"

- name: Assure lmi client app are properly installed
  copy: src={{blddir}}/lmi/client.js dest={{lmi_root}}/public/scripts/ owner=www-data group=www-data mode=644

- name: Assure lmi server app are properly installed
  copy: src={{blddir}}/lmi/server.js dest={{lmi_root}} owner=www-data group=www-data mode=644
  notify:
    - restart lmi