[DEFAULT]

#
# From neutron.vpnaas
#

# Driver to use for scheduling router to a VPN agent (string value)
#vpn_scheduler_driver = neutron_vpnaas.scheduler.vpn_agent_scheduler.LeastRoutersScheduler

# Allow auto scheduling of routers to VPN agent. (boolean value)
#vpn_auto_schedule = true

# Automatically reschedule routers from offline VPN agents to online VPN
# agents. (boolean value)
#allow_automatic_vpnagent_failover = false


[service_providers]

#
# From neutron.vpnaas
#

# Defines providers for advanced services using the format:
# <service_type>:<name>:<driver>[:default] (multi valued)
#service_provider =
