# CUBE SDK

include ../../../../../build.mk

TESTS_LIBS = $(PROJ_LIBDIR)/libcube_sdk.a $(HEX_SDK_LIB_ARCHIVE)

CPPFLAGS += -I$(TOP_SRCDIR)/core/cube_sdk_library/include

include $(HEX_MAKEDIR)/hex_sdk.mk

