# CUBE SDK
# prometheus scrape target generation

# Per-node scrape target lists for the exporters, one file_sd file per exporter.
#
# file_sd rather than static_configs for the same reason lachesis uses it: the compute and
# storage membership is not in cubesys.control.addrs, so config_prometheus cannot know it at
# commit time, and a node joining or leaving must not need a hex_config commit to be scraped.
# Regenerated by cron, like lachesis's.
#
# Every target carries **fqdn** as well as instance. fqdn is the label Watcher's metric_map
# keys host metrics on -- monasca's per-host series were dimensioned `hostname`, and the
# replacement has to answer the same question -- so its value is the node's hostname exactly as
# `cubectl node list` reports it, never an address.
_prometheus_targets_write()
{
    local out=$1
    local role=$2
    local port=$3
    local nodes

    # -r is a role-bitmask match, the same one IsCompute()/IsControl() apply in
    # core/modules/include/role_cubesys.h. Empty output means cubectl/etcd gave no answer --
    # a bootstrap commit that runs before the node registers itself, or a wedged etcd -- never
    # a zero-node cluster, so fail rather than truncate a live list to nothing.
    nodes=$(timeout 20 cubectl node list -j ${role:+-r $role} 2>/dev/null)
    [ -n "$nodes" ] || return 1

    mkdir -p "$(dirname $out)"
    echo "$nodes" | jq -c --arg port "$port" '
        [ .[] | { targets: [ .ip.management + ":" + $port ],
                  labels: { instance: .hostname, fqdn: .hostname } } ]' > "$out.tmp" \
        || { rm -f "$out.tmp" ; return 1 ; }

    # a removed node's target is dropped rather than retained-as-down: removal is deliberate,
    # and a permanent up==0 for it would only be noise
    if cmp -s "$out.tmp" "$out" 2>/dev/null ; then
        rm -f "$out.tmp"
    else
        mv -f "$out.tmp" "$out"
    fi
}

# Called from cron and from config_prometheus's commit. Idempotent; a failure to reach cubectl
# leaves the previous list in place rather than emptying it.
prometheus_exporter_targets()
{
    local dir=/etc/prometheus/targets
    local rc=0

    # node_exporter runs everywhere -- every role has a kernel worth reporting on.
    _prometheus_targets_write $dir/node.json "" 9101 || rc=1

    # ipmi_exporter also runs everywhere, but only says anything useful where there is a BMC.
    # On a VM lab every probe fails and the series simply read as down, which is the same
    # behaviour monasca's ipmi_sensors plugin had there.
    _prometheus_targets_write $dir/ipmi.json "" 9290 || rc=1

    # memcached and httpd are control-plane services, so their exporters only exist there.
    _prometheus_targets_write $dir/memcached.json control 9150 || rc=1
    _prometheus_targets_write $dir/apache.json control 9117 || rc=1

    return $rc
}
